name: Build Application

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Build
      run: |
        echo "Building Three Tier Application"
